version: "3.7"
volumes:
  unifi_mongo_data:
  unifi-config:
services:
  unifi-mongo-db:
    build:
      context: .
      dockerfile_inline: |
        FROM docker.io/mongo:6.0.15-jammy
        COPY ./init-mongo.js /docker-entrypoint-initdb.d/init-mongo.js
    container_name: unifi-mongo-db
    environment:
      - MONGO_USER=${MONGO_USER:-unifi}                     # Default "unifi"
      - MONGO_PASS=${MONGO_PASS:?Mongo Password Required}   # Required
      - MONGO_DBNAME=${MONGO_DBNAME:-unifi}                 # Default "unifi"
    volumes:
      - unifi_mongo_data:/data/db
    restart: unless-stopped
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    depends_on: 
      unifi-mongo-db: 
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MONGO_USER=${MONGO_USER:-unifi}                     # Default "unifi"
      - MONGO_PASS=${MONGO_PASS:?Mongo Password Required}   # Required
      - MONGO_DBNAME=${MONGO_DBNAME:-unifi}                 # Default "unifi"
      - MONGO_HOST=unifi-mongo-db
      - MONGO_PORT=27017
      # - MEM_LIMIT=1024 #optional
      # - MEM_STARTUP=1024 #optional
      # - MONGO_TLS= #optional
      # - MONGO_AUTHSOURCE= #optional
    volumes:
      - unifi-config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      # - 8843:8843 #optional
      # - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped