networks:
  unifi-internal:
  # ---------------------------------------------------------------------------
  # Optional, Use this network or your own if you intend to configure the 
  # unifi-network-application container through a revers proxy, otherwise not needed.
  # ---------------------------------------------------------------------------
  # proxy-network: 
  #   external: true

  # ---------------------------------------------------------------------------
  # If your Docker host is on a different subnet than your unifi devices, 
  # you can use macvlan network to assign a static IP to the unifi-network-application 
  # container so that it can communicate with your unifi devices. Otherwise, you can
  # you may need to use host network mode for unifi-network-application container.
  # Note, make sure to comment out port mappings 3478, 10001, 8080, and 1900 if using 
  # macvlan network with and you want the Unifi UI to be accessible from a reverse proxy 
  # otherwise you have to remove all port mapping as with host network mode.
  # ---------------------------------------------------------------------------
  # unifi-external: 
  #   driver: macvlan
  #   driver_opts:
  #     parent: eth0.1
  #   ipam:
  #     config:
  #       - subnet: 192.168.1.0/24
  #         gateway: 192.168.1.1

# -----------------------------------------------------------------------------
# You can change the volumes' device path if you want, otherwise no need to change, 
# default Docker volume folder location will be used.
# -----------------------------------------------------------------------------
volumes: 
  unifi_mongo_data:
  unifi-config:
  
services:
  unifi-mongo:
    image: portiz93/unifi-mongo:${MONGO_VERSION:-${LATEST_VERSION}}    # Required MONGO_VERSION, Default "${LATEST_VERSION}", specify whatever Mongo version tag you need. DO NOT set 'latest' tag
    container_name: unifi-mongo
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}                    # Required only if using mongodb version < 6.0, otherwise do not set (See official Mongo image)
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?Root Password Required}  # Required only if using mongodb version < 6.0, otherwise do not set  (See official Mongo image)
      - MONGO_USER=${MONGO_USER:-unifi}                     # Default "unifi"
      - MONGO_PASS=${MONGO_PASS:?Mongo Password Required}   # Required
      - MONGO_DBNAME=${MONGO_DBNAME:-unifi}                 # Default "unifi"
    volumes:
      - unifi_mongo_data:/data/db
    # ports:
    #   - 27017:27017  # optional, Default "27017", only port if needed outside of unifi app
    networks:
      - unifi-internal
    restart: unless-stopped
    labels: # IMPORTANT, if you have watchtower, disable auto update for this container
      com.centurylinklabs.watchtower.enable: false   

  unifi-network-application:
    image: linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    hostname: unifi-controller
    depends_on: 
      unifi-mongo: 
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MONGO_USER=${MONGO_USER:-unifi}                     # Required, Default "unifi"
      - MONGO_PASS=${MONGO_PASS:?Mongo Password Required}   # Required, Note some special charactor could cause failure to connect to MondoDB
      - MONGO_DBNAME=${MONGO_DBNAME:-unifi}                 # Required, Default "unifi"
      - MONGO_HOST=unifi-mongo                              # Required, must match the mongo container name
      - MONGO_PORT=27017                                    # Required, Must be that same as the mongo container defined port
      # - MEM_LIMIT=1024                                    # optional
      # - MEM_STARTUP=1024                                  # optional
      # - MONGO_TLS=                                        # optional
      # - MONGO_AUTHSOURCE=                                 # optional
    volumes:
      - unifi-config:/config
    ports:
      - 8443:8443          # Unifi web admin port
      # - 3478:3478/udp      # Unifi STUN port, required for remote access. Unless your controller will never be accessed remotely, you can comment this port.
      - 10001:10001/udp    # Required for AP discovery
      - 8080:8080          # Required for device communication
      - 1900:1900/udp      # Required for Make controller discoverable on L2 network option
      # - 8843:8843          # optional Unifi guest portal HTTPS redirect port
      # - 8880:8880          # optional Unifi guest portal HTTP redirect port
      # - 6789:6789          # optional For mobile throughput test
      # - 5514:5514/udp      # optional Remote syslog port
    networks:
      proxy-network: # optional, Use this network or our own if you intend to configure the unifi-network-application container through a revers proxy, otherwise not needed.
      unifi-internal:
      # unifi-external:
      #   ipv4_address: 192.168.1.11       # Set a static IP address on the macvlan network, must be in the subnet range of the macvlan network 
      #   mac_address: "02:42:c0:a8:01:64" # optional, set a static MAC address if needed
    restart: unless-stopped